# Artificial Intelligence 1 Week 5 Practical
### Goals
This session is designed to give you experience of the numpy library in python.

Numpy is the foundation of practical machine learning and data science:


### By the end of this session you should be able to:

- create simple 2-dimensional numpy arrays filled with zeros, ones or empty
- do 'data slicing' to extract different 'views' from a numpy array
- use functions like shape() to access the sizew of the array
- use simple functions like min() max() and mean() to get statistics about the whole arrays, or particular rows and columns in it

### Before next week you should have
- Completed the exercises below for the Iris dataset
- Expanded the domain-specific knowledge contents of your revision bot with definitions and examples for all the other key concepts covered so far.

### Additional Resources
There is lots of help available for working with numpy- if in doubt, just google your error!

- this has lots of good illustrations and is a five minute read up to "Data Representation": http://jalammar.github.io/visual-numpy/

- this is a great quick start guide to numpy:
  - https://numpy.org/doc/stable/user/quickstart.html
  

- this is a longer walk through but very professional produced with exampels otrun and try : https://www.w3schools.com/python/numpy/numpy_intro.asp

- this ia a good read recommended by Nathan: 

 

# Accessing data from  Python numpy arrays
<img src="slicing.png" style="float:right"><div class="alert alert-block alert-info"> <b>ASIDE: Python arrays and slicing:</b> Python has a <b>numpy</b> module with lots of useful code for doing math, and creating and manipulating arrays of data <br>If we have a 2D numpy array X  we can select just parts of it - i.e. groups of rows, or colums, by "slicing". <br>  We specify the range of rows we want, then the range of columns using X[startRow: endRow, startCol: endCol] <br>
    <ul>
        <li><b>the endRow and endCol are not included in the slice.</b></li>
    <li> If start or end are empty, then the slices goes right from the start or right to the end</li>
    <li> if the start is empty and the end is negative, the slices comes from the end of the row/column</li>
    </ul> 
<b>Example 1:</b>. If we put the letters of my name into a 1-D array  then we can pick out what we want as shown in the cell below. <br>
<b>Example 2</b> (also in the cell below) If we have all the tutors names we could pick out just one row,  or the nth letter in all their names. <br><b>Example 3</b>, if (as in the iris data in this tutorial) X has 150 rows and 4 columns then:
 <ul>
     <li> A = X[ 0 : 50 , :].  A is a 2d array containing the first 50 rows, and all 4 columns</li>
     <li> B = X[ : , 3:].   B is a 1D array with 150 rows and  the columns 3 and onwards (in this case, it is just the last)<br>
     <li> C = X[ 0: 2, 0:4] C is a 2D array with 3 rows and 4 columns <br></div>

In [2]:
import numpy as np

#Example 1
print('Declaring a 1d array')
jimsName = np.array ( ['j','i','m',' ','s','m','i','t','h'])
print(jimsName)
print('extracting a range of values from a 1-D array:')
print( jimsName[0:3])

# Example 2
print('\n Declaring a  a 2D array:')
tutorsNames = np.array([['j','i','m',' ','s','m','i','t','h',' ',' ',' '], 
                        ['c','h','r','i','s',' ','s','i','m','o','n','s'], 
                        ['n','a','t','h','a','n',' ','d','u','r','a','n']],dtype=str)
print(tutorsNames)

print('Extracting the a row from a 2D array - in this cas the second')
print(tutorsNames[1, : ])   # every column of the second row

print('Extracting a range of columns from every row of a 2D array')
print(tutorsNames[ :, 1:5])

# This example uses negative index to read from the end of a slice
print('extracting a specific block of data from a 2D array')
print(tutorsNames[2,-5:])

Declaring a 1d array
['j' 'i' 'm' ' ' 's' 'm' 'i' 't' 'h']
extracting a range of values from a 1-D array:
['j' 'i' 'm']

 Declaring a  a 2D array:
[['j' 'i' 'm' ' ' 's' 'm' 'i' 't' 'h' ' ' ' ' ' ']
 ['c' 'h' 'r' 'i' 's' ' ' 's' 'i' 'm' 'o' 'n' 's']
 ['n' 'a' 't' 'h' 'a' 'n' ' ' 'd' 'u' 'r' 'a' 'n']]
Extracting the a row from a 2D array - in this cas the second
['c' 'h' 'r' 'i' 's' ' ' 's' 'i' 'm' 'o' 'n' 's']
Extracting a range of columns from every row of a 2D array
[['i' 'm' ' ' 's']
 ['h' 'r' 'i' 's']
 ['a' 't' 'h' 'a']]
extracting a specific block of data from a 2D array
['d' 'u' 'r' 'a' 'n']


<div class="alert alert-block alert-warning", style="color:black">
     <h1> Activity 1</h1>
Create and print the following:<ol>
    <li> an array with 3 columns and 2 rows, all filled with zeros</li>
    <li> an array with 3 rows and 2 columns all filld with ones</li>
<li> an array with 8 rows and 8 columns filled with alternating 1s and 0s in a checkerboard pattern.<br>
    HINT: start with an array of zeros then use slicing to put the ones in place</li>
</ol>
                                                                   </div>


In [4]:
myArr = np.zeros((2,3))
print(myArr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
myArr2 = np.ones((3,2))
print(myArr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:

myArr4 = np.zeros((8,8), dtype=int)
myArr4[1::2, ::2] = 1
myArr4[::2, 1::2] = 1
print(myArr4)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


<div class="alert alert-block alert-danger"> Please save your work (click the save icon) then shutdown the notebook when you have finished with this tutorial (menu->file->close and shutdown notebook</div>

<div class="alert alert-block alert-danger"> Remember to download and save your work if you are not running this notebook locally.</div>


